name: test

on:
#   schedule:
#     - cron: '01/5 * * * *'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - name: Install dependencies
        run: |
          mkdir test
      
      - uses: actions/checkout@v4
        with:
          repository: '${{ secrets.ROMOTE_REPO }}'
          token: '${{ secrets.PERSONAL_TOKEN }}'
          path: '${{ github.workspace }}/test/t-repo'
          ref: 'cloud'
      
      - name: Run tests
        run: |
          echo "hello"
          cd ${{ github.workspace }}/test/t-repo
          cargo run --features "cpu-only" -- -c gen.blob -p ${{ secrets.PARAM }} -n ${{ secrets.NUM }}
